In [1]:
import numpy as np
import pandas as pd

In [2]:
# Define your legend dictionary
legend = {'Open': 0, 'High': 1, 'Low': 2, 'Close': 3, 'Vol': 4}

In [3]:
def get_filtered_dataframe(metric, currencies, convert_currencies, updated_currencies, start_date):
    # Initialize a dictionary to hold columns and dataframes for each metric
    fx_columns = [f'{metric} of {symbol}' for symbol in currencies]
    fx_dataframe = pd.DataFrame(columns=fx_columns)
    
    # Populate the DataFrame with data from CSV files for each currency
    for symbol in currencies:
        data = pd.read_csv(f'{symbol}1440.csv', index_col=0, sep='\t', header=None)
        fx_dataframe[f'{metric} of {symbol}'] = data.iloc[:, legend[metric]].copy()

    # Apply conversion for specific currency pairs if needed
    if metric != 'Vol':  # Conversion applies to all metric except 'Vol' metric
        for symbol in convert_currencies:
            column_name = f'Close of {symbol}'
            if column_name in fx_dataframe.columns:
                fx_dataframe[column_name] = (1 / fx_dataframe[column_name])

    # Update column names to reflect the updated currency pairs
    updated_columns = [f'{metric} of {symbol}' for symbol in updated_currencies]
    fx_dataframe.columns = updated_columns

    # Filter the DataFrame starting from the specified start date
    filtered_dataframe = fx_dataframe.loc[start_date:]

    # Forward-fill any missing values
    filtered_dataframe.ffill(inplace=True)

    return filtered_dataframe

In [4]:
metric = 'Close'
currencies = ['AUDUSD', 'NZDUSD', 'USDCAD', 'EURUSD', 'USDCHF']
convert_currencies = ['USDCAD', 'USDCHF']
updated_currencies = ['AUDUSD', 'NZDUSD', 'CADUSD', 'EURUSD', 'CHFUSD']
start_date = '2008-10-16 00:00:00'

In [5]:
filtered_close_dataframe = get_filtered_dataframe(metric, currencies, convert_currencies, updated_currencies, start_date)

filtered_close_dataframe

/var/folders/gx/shg4k1vs1vg0jmxtrsqbm7cc0000gn/T/ipykernel_30176/1233512589.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataframe.ffill(inplace=True)

,Close of AUDUSD,Close of NZDUSD,Close of CADUSD,Close of EURUSD,Close of CHFUSD
0,,,,,
2008-10-17 00:00,0.68827,0.61185,0.845809,1.34052,0.879585
2008-10-19 00:00,0.69444,0.61140,0.845166,1.34418,0.881562
2008-10-20 00:00,0.70225,0.62065,0.839137,1.33373,0.870095
2008-10-21 00:00,0.67460,0.60690,0.823689,1.30052,0.865838
2008-10-22 00:00,0.66355,0.58800,0.795482,1.27701,0.858369
...,...,...,...,...,...
2024-10-21 00:00,0.66537,0.60226,0.722909,1.08153,1.155388
2024-10-22 00:00,0.66812,0.60431,0.723715,1.07962,1.155348
2024-10-23 00:00,0.66341,0.60051,0.722700,1.07803,1.153709
2024-10-24 00:00,0.66341,0.60073,0.721855,1.08237,1.154854
2024-10-25 00:00,0.66010,0.59755,0.719922,1.07945,1.154241

In [6]:
metric_vol = 'Vol'

filtered_vol_dataframe = get_filtered_dataframe(metric_vol, currencies, convert_currencies, updated_currencies, start_date)

filtered_vol_dataframe

/var/folders/gx/shg4k1vs1vg0jmxtrsqbm7cc0000gn/T/ipykernel_30176/1233512589.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_dataframe.ffill(inplace=True)

,Vol of AUDUSD,Vol of NZDUSD,Vol of CADUSD,Vol of EURUSD,Vol of CHFUSD
0,,,,,
2008-10-17 00:00,73459,1107789.0,1779809.0,132203.0,9580952.0
2008-10-19 00:00,2385,62501.0,277126.0,92839.0,425723.0
2008-10-20 00:00,67814,1046929.0,959098.0,712195.0,5925987.0
2008-10-21 00:00,76411,1342718.0,1813691.0,712153.0,8321884.0
2008-10-22 00:00,76989,1526125.0,2023925.0,713145.0,8763108.0
...,...,...,...,...,...
2024-10-21 00:00,58185,76078.0,115387.0,185319.0,61201.0
2024-10-22 00:00,64223,70869.0,124475.0,195245.0,67413.0
2024-10-23 00:00,92138,64617.0,149680.0,236731.0,64995.0
2024-10-24 00:00,76409,74671.0,149473.0,255090.0,83310.0
2024-10-25 00:00,66127,69768.0,132084.0,156023.0,60718.0